config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get('/', to: "welcome#index")

  # get('/posts', to: "posts#index")
  # get('/posts/show/:id', to: "posts#show", as: :post)
  # get('/posts/new/', {to: "posts#new", as: :new_post})

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get('/comments', to: "comments#show")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :category, optional: true
  belongs_to :user, optional: true

  validates :title, { presence: {message: "must be provided"},
                    uniqueness: true }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :email, :password, :password_confirmation
  has_secure_password

  validates_uniqueness_of :email

  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  before_create { generate_token(:auth_token)}

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end

  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user # :user_signed_in?

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: "Please sign in"
    end
  end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_comment, only: [:destroy]

  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to @post, notice: "Comment Created"
    else
      render 'posts/show'
    end
  end

  def destroy
    @post = @comment.post
    @comment.destroy

    redirect_to post_path(@post), notice: "Comment Deleted"
  end

  private

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post created"
      redirect_to posts_path
    else
      flash.now[:alert] = "Please fix errors"
      render :new
    end
  end

  def show
    # @post = Post.find params[:id]
    @comment = Comment.new
    @comments = @post.comments
  end
  
  def index
    @posts = Post.all.order(updated_at: :DESC)
  end

  def edit
    # @post = Post.find params[:id]
  end

  def update
    # @post = Post.find params[:id]

    if @post.update(post_params)
      redirect_to posts_path, notice: "Successfully Updated"
    else
      flash.now[:alert] = 'Please fix errors'
      render :new
    end

  end

  def destroy
    # @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path,notice: "Post Deleted"
  end

  private

  def post_params
    params.require(:post).permit([:title, :body, :category_id])
  end

  def find_post
  @post = Post.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    @isLogin = true
    render 'users/new'
  end

  def create
    # byebug
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id

      redirect_to posts_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Wrong email or password"
      # render :new
      render 'users/new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path, notice: "Signed out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @isLogin = false

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path, notice: "Thank you for signing up"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/show.html.erb
<h1>Comments</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogCrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%#= javascript_include_tag 'application' %>

  </head>

  <body>
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" arial-controls ="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand fa fa-envelope fa-2x" href="#"></a>
          </div>

          <div class="collapse navbar-collapse" id="navbar">

            <ul class="nav navbar-nav navbar-right">
              <li><form class="navbar-search navbar-form navbar-left" action="index.html" method="post">
                <input type="text" class="form-control" placeholder="Search..." name="" value="">
              </form>
            </li>
            <% if current_user.present? %>
              <li><a href="javascript:void(0)">Welcome <span><%= current_user.first_name %></span></a></li>
              <li></li>
              <li><%= link_to "Log Out", logout_path, method: 'delete'  %></li>
            <% else %>
            <li><%= link_to 'Sign up', signup_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
            <% end %>
            </ul>

            <ul class="nav navbar-nav">
              <li><a class="nav-link" href="#">About</a></li>
              <li><a class="nav-link" href="#">Contact</a></li>
            </ul>

          </div>
        </div>
  </nav>

  <div style="margin-top: 50px;" class="img-responsive bgImage">
    <h1><%= link_to "Posts", posts_path %></h1>

    <% if flash[:notice] %>
      <div class='alert alert-success'><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class='alert alert-danger'><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>

    <div style="margin-top: 40px;"></div>

    <nav class="footer navbar navbar-fixed-bottom navbar-inverse bg-primary">
      <div class="container">
        <div class="" style="display: flex; flex-direction: row; justify-content: space-around;">
          <a class="fa fa-facebook fa-3x flinks" href="#"></a>
          <a class="fa fa-envelope fa-3x flinks" href="#"></a>
          <a class="fa fa-medium fa-3x flinks" href="#"></a>
          <a class="fa fa-twitter fa-3x flinks" href="#"></a>
          <a class="fa fa-instagram fa-3x flinks" href="#"></a>
        </div>
      </div>
    </nav>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= @post.errors.full_messages.join(', ') %>

<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
    <%= f.label :category %>
    <%= f.collection_select :category_id,
              Category.all,
              :id, # this represent the method that is used for the option tag's value
              :name, # this repesents the method that is used for the option tag's text
              include_blank: true,
              prompt: 'Choose a category'
              %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">

<div class="container visible-lg">
  <div class="row">
    <div class="col-lg-8">
      <%= image_tag 'prince.jpg', class: "img-responsive" %>
    </div>

    <div class="col-lg-4">
      <h3>Most Liked</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Magnam cum et totam accusantium? Veritatis, voluptatum,
        consequatur? Similique atque maxime recusandae dignissimos
        esse, quaerat magnam sit excepturi, ab, architecto facilis
        earum.
      </p>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-lg-1">
      <i class="fa fa-heart-o fa-2x" aria-hidden="true" style="display: inline"></i>
      <h4 style="display: inline">476</h4>
    </div>
    <div class="col-lg-6">
      <%= link_to 'Add a Post', '/posts/new', class: "btn btn-primary btn-block" %>
    </div>
    <div class="col-lg-1">
      <i class="fa fa-bookmark-o fa-2x" aria-hidden="true" style="float: right;"></i>
    </div>

  </div>
  <div class="row">
    <div class="col-lg-8">
      <h3>Post Title</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Magnam cum et totam accusantium? Veritatis, voluptatum,
        consequatur? Similique atque maxime recusandae dignissimos
        esse, quaerat magnam sit excepturi, ab, architecto facilis
        earum.
      </p>
      <h4><a href="#">Post Author Name: <%= @post&.user&.full_name %></a></h4>
      <i><%= Time.now() %></i>
    </div>
  </div>
</div>
<br>
<br>



  <!-- <div class="row">

      <div class="col-sm-12 col-md-12 col-lg-12 ">
        <%= link_to 'Add a Post', new_post_path, class: "btn btn-primary btn-block" %>
      </div>

  </div> -->
      <br />
            <% @posts.each_slice(3) do |group| %>
              <div class="row">
                <% group.each do |post| %>
                  <div class="col-sm-12 col-md-12  col-lg-4 col-xl-3 posts">
                    <%= image_tag 'prince.jpg', class: "img-responsive" %>
                    <div>
                      <i class="fa fa-heart-o fa-2x" aria-hidden="true" style="display: inline"></i>
                      <h4 style="display: inline"><%= post.id %></h4>
                      <i class="fa fa-bookmark-o fa-2x" aria-hidden="true" style="float: right;"></i>
                    </div>

                    <%= link_to post.title, post_path(post) %>

                    <br />
                    <br />
                    <!-- <p><string>Category:<br /> </string><%= post&.category&.name %></p> -->
                    <p><string>Body:<br />  </string><%= post.body %></p>
                    <h4><a href="#">Post Author Name</a></h4>
                    <div><%= post.created_at.strftime("%B %d, %Y") %></div>
                  </div>
                  <hr class="hidden-lg">
                <% end %>
            </div>
          <% end %>

</div>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-8 pull-left">
    <h3><%= @post.title %></h3>
  </div>

  <div class="col-lg-2 pull-right">
    <i class="fa fa-heart-o fa-2x" aria-hidden="true" style="display: inline">&nbsp;</i>
    <h4 style="display: inline"><%= @post.id %>&nbsp;</h4>
    <i class="fa fa-bookmark-o fa-2x" aria-hidden="true"></i>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <%= image_tag 'prince.jpg', class: "img-responsive show_post_img" %>
  </div>
</div>

<div class="container">
  <!-- <div class="jumbotron"> -->
    <div class="row">
      <div class="col-lg-12">

        <h3><%= @post.title %></h3>
        <!-- <h3><%= @post&.category&.name %></h3> -->
        <p><%= @post.body %>
          <div class="row">
          <div class="pull-left"><h3><%= @post&.category&.name %></h3></div>
          <div class="pull-right"><i><%= @post.created_at.strftime("%B %d, %Y") %></i></div>
          </div>
        </p>
        <br>
        <br>
      </div>


      <div class="col-lg-6 col-lg-offset-3">
          <a href="./<%= @post.id %>/edit" role="button">
            <span style="font-size: 20px" class="glyphicon glyphicon-edit" arial-hidden="true"</span>
          </a>

          <% if user_signed_in? && @post.user == current_user %>
          <%= link_to("", post_path(@post),
                                method: :delete,
                                data: {confirm: "Are you sure?"}, class: "glyphicon glyphicon-remove p_delete")%>
          <% end %>
          <%= link_to "Back", posts_path, class: "btn btn-primary btn-default pull-right" %>
          <h4>Author's Name: <%= @post.user&.full_name %></h4>
      </div>


    </div>
    <br>
    <br>

    <% if user_signed_in? && current_user != @post.user %>
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= form_for [@post, @comment] do |f| %>
            <%= f.text_area :body, placeholder: 'Add a comment', class: "comment-textarea" %>
            <%= f.submit "Add", class: "btn btn-default pull-right" %>
          <% end %>
        </div>
      </div>
    <% end %>


    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <h3>Comments</h3>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">

        <h5>
            <% @comments&.each do |comment| %>
              <%= comment.body %>
              <% if user_signed_in? && comment.user == current_user %>
                <%= link_to("", [@post, comment],
                method: :delete,
                data: {confirm: "Are you sure?"},
                class: "glyphicon glyphicon-remove p_delete pull-right")%>
                <% end %>
        </h5>
        <br>
        <hr>
        <% end %>
      </div>
    </div>



  <!-- </div> -->
</div>

app/views/users/new.html.erb
<div class="form">

      <ul class="tab-group">
        <li class="tab <% unless @isLogin %> active <% end %>"><a href="/signup">Sign Up</a></li>
        <li class="tab <% if @isLogin %> active <% end %>"><a href="/login">Log In</a></li>
      </ul>

      <div class="tab-content">
        <div id="signup" class="<% unless @isLogin %> show <% else %> hide <% end %> ">
          <h2>Sign Up for Free</h2>

        <%= form_for (@user || User.new) do |f| %>
          <form action="/signup" method="post">

          <div class="top-row">
            <div class="field-wrap">
              <!-- <label>
                First Name<span class="req">*</span>
              </label> -->
              <%= f.text_field :first_name, placeholder: 'First Name', class: 'req' %>
            </div>

            <div class="field-wrap">
              <%= f.text_field :last_name, placeholder: 'Last Name' %>
            </div>
          </div>

          <div class="field-wrap">
            <%= f.email_field :email, placeholder: 'Email' %>
          </div>

          <div class="field-wrap">
              <%= f.password_field :password, placeholder: 'Password' %>
          </div>

          <div class="field-wrap">
              <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>
          </div>

          <div class="action"><%= f.submit :'Get Started', class: "button button-block" %></div>

          </form>
        <% end %>
        </div>



        <div id="login" class="<% if @isLogin %> show <% else %> hide <% end %> ">
          <h2>Welcome Back!</h2>

          <%= form_tag sessions_path do %>

          <div class="field-wrap">
            <%= text_field_tag :email, params[:email], placeholder:'example@example.example' %>
          </div>

          <div class="field-wrap">
            <%= password_field_tag :password, params[:email], placeholder:'Password' %>
          </div>

          <!-- <p class="forgot"><a href="#">Forgot Password?</a></p> -->

          <!-- <button class="button button-block"/>Log In</button> -->
          <div class="action"><%= submit_tag "Log In", class: "button button-block" %></div>

           <% end %>
        </div>

      </div><!-- tab-content -->

</div> <!-- /form -->

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
  <div class="col-lg-6 col-lg-offset-3">
  <p style="color: white;margin-top: 150px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  </div>
</div>